apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true
  labels:
    type: group-helmrelease-values

configMapGenerator:
  - name: kube-prometheus-stack-group-helmrelease-values
    namespace: kube-prometheus-stack
    files:
      - values.yaml=kube-prometheus-stack-group-helmrelease-values.yaml

configurations:
  - kustomizeconfig.yaml
