apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - policy-reporter-ingress.yaml

generatorOptions:
  disableNameSuffixHash: true
  labels:
    type: group-helmrelease-values

configMapGenerator:
  - name: policy-reporter-group-helmrelease-values
    namespace: policy-reporter
    files:
      - values.yaml=policy-reporter-group-helmrelease-values.yaml

configurations:
  - kustomizeconfig.yaml
