apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: external-snapshotter-crds
  namespace: flux-system
spec:
  interval: 5m
  path: flux/cluster-apps/external-snapshotter/external-snapshotter-crds-kustomization
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
