apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ww-gitops
  namespace: ww-gitops
spec:
  chart:
    spec:
      chart: weave-gitops
      sourceRef:
        kind: HelmRepository
        name: ww-gitops
        namespace: flux-system
  interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: ww-gitops-group-helmrelease-values
      optional: true
    - kind: ConfigMap
      name: ww-gitops-cluster-helmrelease-values
      optional: true
