apiVersion: v1
kind: Secret
metadata:
    name: cluster-apps-secrets
    namespace: flux-system
type: Opaque
data:
    USER_NAME: ENC[AES256_GCM,data:Ma3ubZhwY0guODUZOxj+yw==,iv:ZAgu5nSWoBZ1J9SevniTeSJAgAMGg7ThxkmhCSuIj5o=,tag:z88tkOduyIhp9bxXBttE8Q==,type:str]
    PASSWORD: ENC[AES256_GCM,data:vpCclhFH5KE=,iv:chhi5pgEEHLHPVtmnDGEs1xrHZA/QExu/nfe7YbknSM=,tag:Nu+QPqv7KudJgmuGAR0rLg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-central-1:729560437327:alias/sops
          created_at: "2022-06-17T18:37:50Z"
          enc: AQICAHi6LQQvIhnSAvomoXCu+jcBZlWiugdvqoPaQnWm1x1PbwEz6YBuUeHM9FTiELnr5QE5AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMDhDMD4po8XwGsyukAgEQgDv1EArIHiIsDmSqQe21WQj6UE6/SAzCn/JvDT/SRIhseA2UzetcRCnk9CwXKtosNJqdj7+rXXNxsotmjg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-06-17T18:38:43Z"
    mac: ENC[AES256_GCM,data:dG3UXgYKXixpT1jCoNowcXZ0zDgaFpdBBFT4AJCVriTMaaoPqum84Mxo7v3+TSftaExzJJrjpM+8e0iYW8zm4/QJMkdgTr2CGrZBygBAYZysiDD8oK9+4+rnM0nZENwSGp2GMPpES1S3Z2d+6G82zKhSiQpkwihcGVHj4rwGz5k=,iv:8WmdQPadNvufEAjm+z4qej0PLt2Iyz0laHj0Nhh/y4g=,tag:0X5oTPMqjk2cZgXDUXvJNQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
