# https://github.com/dexidp/helm-charts/blob/master/charts/dex/values.yaml
config:
  issuer: https://dex.${CLUSTER_FQDN}
  storage:
    type: kubernetes
    config:
      inCluster: true
  oauth2:
    skipApprovalScreen: true
  # Connectors are defined per cluster - arrays can not be merged in helm: https://stackoverflow.com/questions/59394422/helm-charts-with-multiple-lists-in-multiple-values-files
  # connectors:
  staticClients:
    - id: oauth2-proxy.${CLUSTER_FQDN}
      redirectURIs:
        - https://oauth2-proxy.${CLUSTER_FQDN}/oauth2/callback
      name: OAuth2 Proxy
      secret: oauth2-proxy-${OAUTH2_PROXY_SECRET}
  enablePasswordDB: false
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: dex.${CLUSTER_FQDN}
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - dex.${CLUSTER_FQDN}
serviceMonitor:
  enabled: true
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
