apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true
  labels:
    type: cluster-helmrelease-values

configMapGenerator:
  - name: metrics-server-cluster-helmrelease-values
    namespace: metrics-server
    files:
      - values.yaml=metrics-server-cluster-helmrelease-values.yaml

configurations:
  - kustomizeconfig.yaml
