apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: karpenter
  namespace: karpenter
spec:
  chart:
    spec:
      chart: karpenter
      sourceRef:
        kind: HelmRepository
        name: karpenter
        namespace: flux-system
      version: 0.37.0
  interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: karpenter-group-helmrelease-values
      optional: true
    - kind: ConfigMap
      name: karpenter-cluster-helmrelease-values
      optional: true
