skip-check:
  # The build output cannot be affected by user parameters other than the build entry point and the top-level source location. GitHub Actions workflow_dispatch inputs MUST be empty
  - CKV_GHA_7
  # Image should use digest
  - CKV_K8S_43
  # Ensure Terraform module sources use a commit hash
  - CKV_TF_1

skip-path:
  - clusters/aws-dev-mgmt/flux/cluster-apps-secrets/cluster-apps-secrets.yaml
  # Skip all flux manifests
  - flux-system/gotk-components.yaml
  - flux-system/gotk-sync.yaml
  - flux-system/kustomization.yaml
  - flux/kustomization.yaml
  # Skip https://raw.githubusercontent.com/aws/secrets-store-csi-driver-provider-aws/main/deployment/aws-provider-installer.yaml
  - flux/cluster-apps/secrets-store-csi-driver-provider-aws/secrets-store-csi-driver-provider-aws-kustomization/kustomization.yaml
