skip-check:
  # Skip ArgoCD checks
  - CKV_ARGO_1
  - CKV_ARGO_2

skip-path:
  # Skip all flux manifests
  - flux-system/gotk-components.yaml
  - flux-system/gotk-sync.yaml
  - flux-system/kustomization.yaml
  - flux/kustomization.yaml
