skip-check:
  # Skip ArgoCD checks
  - CKV_ARGO_1
  - CKV_ARGO_2
  # Ensure that the seccomp profile is set to docker/default or runtime/default
  - CKV_K8S_31
  # Image should use digest
  - CKV_K8S_43

skip-path:
  # Skip all flux manifests
  - flux-system/gotk-components.yaml
  - flux-system/gotk-sync.yaml
  - flux-system/kustomization.yaml
  - flux/kustomization.yaml
  # Skip https://raw.githubusercontent.com/aws/secrets-store-csi-driver-provider-aws/main/deployment/aws-provider-installer.yaml
  - flux/cluster-apps/secrets-store-csi-driver-provider-aws/secrets-store-csi-driver-provider-aws-kustomization/kustomization.yaml
