apiVersion: v1
kind: ServiceAccount
metadata:
  name: kuard
  namespace: kuard
  labels:
    app: kuard
  annotations:
    eks.amazonaws.com/role-arn: arn:${AWS_PARTITION}:iam::${AWS_ACCOUNT_ID}:role/${CLUSTER_NAME}-iamserviceaccount-kuard
