apiVersion: v1
kind: Secret
metadata:
    name: cluster-apps-secrets
    namespace: flux-system
type: Opaque
data:
    COOKIE_SECRET: ENC[AES256_GCM,data:TZPnegRZ4HO8JajyG+KNaPFUtANS3aNx,iv:OlCgt9G87RCwa4wVxAgIXuj5w1XQqkY1QIClS+p8XeE=,tag:7w+spTq9IbMJ4Qa5qsIGqQ==,type:str]
    CROSSPLANE_AWS_KUARD_SECRET_USERNAME_BASE64: ENC[AES256_GCM,data:8aN/XQSLu+yMVfeg92rlp+vbBz1+xtV++dO9pzVIcHF3HmTw4EaOngZcJnU=,iv:FThz4j23mhheRX+bxfoBJ36klGhf701dwbOG20EtW6c=,tag:L+/aJEeBSEFNEq529HbCOQ==,type:str]
    CROSSPLANE_AWS_KUARD_SECRET_PASSWORD_BASE64: ENC[AES256_GCM,data:qQbiKyFtpCDuT/al9Psdd4CszehSOH/HIp0dWQLMw7RcgWJD/q4vs4YcIMY=,iv:oHHZGvdGTkibCK01CjI6CSZrfu72ckwnSlsBj9bNWKo=,tag:iLYZFKYGOu2j4iD1fjs7JA==,type:str]
    OAUTH2_PROXY_SECRET: ENC[AES256_GCM,data:S2KxFy//eqIcHTAWRtAYrdBFfxiiYRjVGKhY57Ee14zZsi9uSwRJ1ExpTc6u0ZCi3PkfpjXqIG3WYzlSOGUX4VwQq7yS4M+XXBvuyLn1dCYxn+VSF0GcfvELPyVHMvCF,iv:eK3ESmrBRRqInPspl7+FIfEISQglE1ih6AX15bPIS1I=,tag:45EWJ5aYb2TOemd0cZhRxQ==,type:str]
    SLACK_WEBHOOK_URL: ENC[AES256_GCM,data:TEbMRHgo5034xfy6t2SFHkf9iYQIUGhHlh6AOU+41rRIRcLI1VNLh04eEYAWJ2FPnOk39XYvT0d6nCVA0rU4F2vQg9TBSMaxPPTyZ3xaoxeq7/crQYGaJN4sS4rqoYR3fiMLWRyzJhr0OdQW,iv:wBOU3MyKtRKw7xtNZR6yHRx6e/4LITGKKstkrKmjXTc=,tag:gor8tFVVi95lTRZPi870IQ==,type:str]
    SLACK_WEBHOOK_URL_BASE64: ENC[AES256_GCM,data:JdW60w+nUFx4BfrfsfXmmUGP1lLe95kf2V2OYgBC76cUwz/GrJDtlT6FWLlfKGWLzh0L0ij+Lsl88oc3mD17F0UzCC9gS/ZDdnNkI88XthQot15CZBE+BQ6hOMHzsNGLstlOmWk0JgSEt67bb9xnly2jpVqKnKCO5KrZD6vaoYs6HsG6xDfIcJ3PplRWb2rP,iv:OUU+S8j5BGpeZRNfEb39L2BT29j8yNJymIZLLhCefGo=,tag:1Ft0U3MkhwWkaWqU6qypsA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-central-1:729560437327:alias/sops
          created_at: "2022-06-17T18:33:24Z"
          enc: AQICAHi6LQQvIhnSAvomoXCu+jcBZlWiugdvqoPaQnWm1x1PbwEhTqsFEQT0jvPZy38hzgTIAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMgElGoHUf1Ua7SXNMAgEQgDulYh8EmRG1iRwuyVieUkc6cQHw0aum45JjXO7Vi4IsDksojSSVJs8AbQqnviuoP7hCgshVbcFHHhJA6Q==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-27T04:28:18Z"
    mac: ENC[AES256_GCM,data:BfSNadE44yagrayKfpbTVFp/Z6DKumzd+o83ZuWG3gYaGc8m3pQpBB4NLR+L89gjr6brMV+xAxZVSsio6iyQ88WWvAtyGVMdjRwhdKfHBkxFKKZR+vZAb/E/X+B1oDD5uObk2a1mQajc0vkr0OvwpYURiI2qWueOq/AZCVPOXtw=,iv:cGVnChvDgdbizVkMChQMgh0fU85Ahu3u4gNP5b3IFKM=,tag:v/C82gP8/xsYelOUXRfGQA==,type:str]
    pgp:
        - created_at: "2022-07-07T06:22:49Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFOA4duewNlKmHnEAf9EnHgboWtazl/TFR2FHWt0X0Cm5XcR6yA0hRoaa5UWZpf
            zeh+kx6Y0ugAhSOiyl5c82RUimeBjedUynXMoizt/bVqGRP9q3AScJQjwgCvhtmw
            l0AKoQynP7qY3apil2nAD0ESziMJILICLhd3S98L7FjB4disdsDI90N4FWtx6WB1
            6Xy5a9/lzPQN6LVo1x4YsAo0NQtI6CaauXgv3VqDQHvjg9bwP8Ar0xnrM1klzkLZ
            Re4Mle/Lr37AQqqVb5edej0zxGHBkZEPBrV1qNwRMUYwGS4UPYitwb+psuCMriWE
            YoF/2b0QbHS8s2DH+x7Y0yih0DgD6g/EuXhGbdSkDgf/WwYi9ZKTij+ZUveT9+sh
            vbeewmgjdebFlM1hRXQ9fvUeuSyjQM2eSWgaxjakV/e+uEbYWnWUmfSC72PoaJfg
            SneCIxk/cMGp11SHG0vYIUhQHd4hQ0fcVLYZiRdFS1/6hLj50kyfK8+LUdC+6pRd
            YCFG82NS0YeV7kz02VbqdWL1MZoBlpRF4hrtCNVTgFl0r09Lc0lTihSzYS7PNTx2
            nAOXjzIrjAreR0HQaGtTAZCDETcy2MZIcXdtfhs1gP0YIIKNGGlDBj700MAFmzrl
            QvvWj/ZXPPOUkV9CLcH/n8YBwz15o4nWaasMMFf0GQWnML8InCvv3ZE62EJjcKNv
            vtJRAZyE3GIAge2h64AgwQqUGuU7akbGfvW3F5QS+Z+KMYMM1Z6C/N8qPJMN3eaf
            RIC6lvTQfB3Uivpx9Y51dZfr/UAH+/0A7N6Ge2VIr5bGf+iQ
            =/dKp
            -----END PGP MESSAGE-----
          fp: 431A7F3379B5B00519077B732BD87EC4BA898363
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
