apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  chart:
    spec:
      chart: kyverno
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: flux-system
      version: 3.2.4
  interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: kyverno-group-helmrelease-values
      optional: true
    - kind: ConfigMap
      name: kyverno-cluster-helmrelease-values
      optional: true
