apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: secrets-store-csi-driver
  namespace: flux-system
spec:
  interval: 5m
  path: flux/cluster-apps/secrets-store-csi-driver/secrets-store-csi-driver-helmrelease-kustomization
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
