apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true
  labels:
    type: group-helmrelease-values

configMapGenerator:
  - name: ingress-nginx-group-helmrelease-values
    namespace: ingress-nginx
    files:
      - values.yaml=ingress-nginx-group-helmrelease-values.yaml

configurations:
  - kustomizeconfig.yaml
