apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-init
  namespace: argocd
spec:
  project: argocd-init-project
  source:
    repoURL: https://github.com/ruzickap/k8s-tf-eks-gitops
    targetRevision: ${targetRevision}
    path: ${path}
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
