apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd-init-project
  namespace: argocd
spec:
  description: Temporary ArgoCD Project for argocd-core
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
