AWSTemplateFormatVersion: 2010-09-09

Parameters:
  UserName:
    Description: User Name which will be allowed to access Key
    Type: String
    Default: aws-cli

Resources:
  KMSKey:
    Type: AWS::KMS::Key
    UpdateReplacePolicy: Retain
    DeletionPolicy: Delete
    Properties:
      Description: "KMS Key used by SOPS to encrypt secrets"
      PendingWindowInDays: 7
      EnableKeyRotation: true
      KeyPolicy:
        Version: 2012-10-17
        Statement:
          - Sid: Enable Root IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:root"
            Action: "kms:*"
            Resource: "*"
          - Sid: Enable User Permissions
            Effect: Allow
            Principal:
              AWS:
                - !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:user/${UserName}"
                - !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:role/GitHubOidcFederatedRole"
            Action:
              - "kms:Encrypt"
              - "kms:Decrypt"
              - "kms:ReEncrypt*"
              - "kms:GenerateDataKey*"
              - "kms:DescribeKe"
            Resource: "*"

  KMSKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/sops
      TargetKeyId: !Ref KMSKey

Outputs:
  KMSKey:
    Value: !Ref KMSKey
  KMSKeyAlias:
    Value: !Ref KMSKeyAlias
