apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  chart:
    spec:
      chart: podinfo
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
      version: 6.1.7
  interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: podinfo-main-helmrelease-values
      optional: true
    - kind: ConfigMap
      name: podinfo-group-helmrelease-values
      optional: true
    - kind: ConfigMap
      name: podinfo-cluster-helmrelease-values
      optional: true
