apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keycloak
  namespace: flux-system
spec:
  dependsOn:
    # ingress + cert-manager-certificate dependency is needed for other apps like oauth2-proxy which tries to connect to keycloak when they are starting
    - name: cert-manager-certificate
    - name: cnpg-db01
    - name: ingress-nginx
    - name: kube-prometheus-stack
  interval: 5m
  path: flux/cluster-apps/keycloak/keycloak-helmrelease-kustomization
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
