apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - karpenter-kustomization.yaml

generatorOptions:
  disableNameSuffixHash: true
  labels:
    type: group-helmrelease-values

configMapGenerator:
  - name: karpenter-group-helmrelease-values
    namespace: karpenter
    files:
      - values.yaml=karpenter-group-helmrelease-values.yaml

configurations:
  - kustomizeconfig.yaml
