apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: dex
  namespace: flux-system
spec:
  dependsOn:
    # ingress + cert-manager-certificate dependency is needed for other apps like oauth2-proxy which tries to connect to dex when they are starting
    - name: cert-manager-certificate
    - name: ingress
    - name: kube-prometheus-stack
  interval: 5m
  path: flux/cluster-apps/dex/dex-helmrelease-kustomization
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
