apiVersion: secretsmanager.aws.crossplane.io/v1alpha1
kind: Secret
metadata:
  name: secretsmanager-kuard-secret
  namespace: crossplane-system
spec:
  providerConfigRef:
    name: aws-providerconfig
  forProvider:
    region: ${AWS_DEFAULT_REGION}
    description: "Secret for kuard app running on ${CLUSTER_FQDN}"
    forceDeleteWithoutRecovery: true
    stringSecretRef:
      name: kuard-secret
      namespace: crossplane-system
