apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  chart:
    spec:
      chart: keycloak
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: 9.6.0
  interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: keycloak-main-helmrelease-values
      optional: true
    - kind: ConfigMap
      name: keycloak-group-helmrelease-values
      optional: true
    - kind: ConfigMap
      name: keycloak-cluster-helmrelease-values
      optional: true
