apiVersion: v1
data:
  password: ${CNPG_DB01_SUPERUSER_PASSWORD_BASE64}
  username: ${CNPG_DB01_SUPERUSER_USERNAME_BASE64}
kind: Secret
metadata:
  name: cnpg-db01-superuser
  namespace: cnpg-db01
type: kubernetes.io/basic-auth
---
apiVersion: v1
data:
  password: ${CNPG_DB01_KEYCLOAK_PASSWORD_BASE64}
  username: ${CNPG_DB01_KEYCLOAK_USERNAME_BASE64}
kind: Secret
metadata:
  name: cnpg-db01-keycloak-keycloak
  namespace: cnpg-db01
type: kubernetes.io/basic-auth
