apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: oauth2-proxy-keycloak
  namespace: flux-system
spec:
  dependsOn:
    - name: kube-prometheus-stack
    - name: keycloak
  interval: 5m
  path: flux/cluster-apps/oauth2-proxy-keycloak/oauth2-proxy-keycloak-helmrelease-kustomization
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
