apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-provider
  namespace: flux-system
spec:
  interval: 5m
  path: flux/cluster-apps/flux-alert-provider/flux-provider-kustomization
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-apps-vars-terraform-secret
      - kind: Secret
        name: cluster-apps-secrets
      - kind: Secret
        name: cluster-apps-group-secrets
