apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-alert
  namespace: flux-system
spec:
  dependsOn:
    - name: flux-provider
  interval: 5m0s
  path: flux/cluster-apps/flux-alert-provider/flux-alert-kustomization
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
