apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ww-gitops
  namespace: flux-system
spec:
  dependsOn:
    - name: kube-prometheus-stack
  interval: 5m
  path: flux/cluster-apps/ww-gitops/ww-gitops-helmrelease-kustomization
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
