apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true
  labels:
    type: group-helmrelease-values

configMapGenerator:
  - name: kyverno-group-helmrelease-values
    namespace: kyverno
    files:
      - values.yaml=kyverno-group-helmrelease-values.yaml

configurations:
  - kustomizeconfig.yaml
