apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-secrets
  namespace: flux-system
spec:
  # detect drift and undo kubectl edits every minute
  interval: 1m
  # Variables are taken from `flux-system/gotk-sync.yaml` stored in Secret `cluster-apps-vars-terraform-secret`
  path: ${CLUSTER_PATH}/flux/cluster-apps-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  decryption:
    provider: sops
