apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: policy-reporter
  namespace: flux-system
spec:
  dependsOn:
    - name: kyverno
    - name: kube-prometheus-stack
  interval: 5m
  path: flux/cluster-apps/policy-reporter/policy-reporter-helmrelease-kustomization
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
