# https://github.com/argoproj/argo-helm/blob/6ff050f6f57edda1e6912ef0bb17d085684e103e/charts/argo-cd/values.yaml#L1222-L1253
applications: []
# - name: guestbook
#   namespace: argocd
#   additionalLabels: {}
#   additionalAnnotations: {}
#   finalizers:
#   - resources-finalizer.argocd.argoproj.io
#   project: guestbook
#   source:
#     repoURL: https://github.com/argoproj/argocd-example-apps.git
#     targetRevision: HEAD
#     path: guestbook
#     directory:
#       recurse: true
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: guestbook
#   syncPolicy:
#     automated:
#       prune: false
#       selfHeal: false
#   ignoreDifferences:
#   - group: apps
#     kind: Deployment
#     jsonPointers:
#     - /spec/replicas
#   info:
#   - name: url
#     value: https://argoproj.github.io/
