apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: remove-tf-flux-main
  secretRef:
    name: flux-system
  url: ssh://git@github.com/ruzickap/k8s-tf-eks-gitops.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/aws-dev-mgmt2/mgmt02.k8s.use1.dev.proj.aws.mylabs.dev/flux
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      # ConfigMap containing variables like CLUSTER_FQDN, CLUSTER_NAME, CLUSTER_PATH, ...
      # They are defined in the Terraform flux section: resource "kubernetes_config_map" "cluster-apps-vars-terraform-secret"
      - kind: Secret
        name: cluster-apps-vars-terraform-secret
