# https://github.com/kyverno/kyverno/blob/main/charts/kyverno/values.yaml
replicaCount: 3
extraArgs:
  - --clientRateLimitQPS=20
  - --clientRateLimitBurst=50
webhooksCleanup:
  enable: true
admissionController:
  serviceMonitor:
    enabled: true
cleanupController:
  serviceMonitor:
    enabled: true
reportsController:
  serviceMonitor:
    enabled: true
backgroundController:
  serviceMonitor:
    enabled: true
