apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # renovate: datasource=github-tags depName=kubernetes-csi/external-snapshotter extractVersion=^(?<version>.*)$
  - https://github.com/kubernetes-csi/external-snapshotter//deploy/kubernetes/snapshot-controller?ref=v6.2.2
