apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cluster-autoscaler
  namespace: cluster-autoscaler
spec:
  chart:
    spec:
      chart: cluster-autoscaler
      sourceRef:
        kind: HelmRepository
        name: autoscaler
        namespace: flux-system
      version: 9.28.0
  interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: cluster-autoscaler-group-helmrelease-values
      optional: true
    - kind: ConfigMap
      name: cluster-autoscaler-cluster-helmrelease-values
      optional: true
