apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      version: v1.9.0
  interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: cert-manager-main-helmrelease-values
      optional: true
    - kind: ConfigMap
      name: cert-manager-group-helmrelease-values
      optional: true
    - kind: ConfigMap
      name: cert-manager-cluster-helmrelease-values
      optional: true
