apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../flux/sources/kubernetes-dashboard
  - ../../../flux/sources/podinfo

  - ../../../flux/cluster-apps/kubernetes-dashboard
  - ../../../flux/cluster-apps/podinfo

  - kubernetes-dashboard
  - podinfo
