apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true
  labels:
    type: cluster-helmrelease-values

configMapGenerator:
  - name: podinfo-cluster-helmrelease-values
    namespace: podinfo
    files:
      - values.yaml=podinfo-cluster-helmrelease-values.yaml

configurations:
  - kustomizeconfig.yaml
