apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps
  namespace: flux-system
spec:
  dependsOn:
    - name: sources
    - name: cluster-apps-secrets
  # detect drift and undo kubectl edits every minute
  interval: 1m
  # Variables are taken from `flux-system/gotk-sync.yaml` stored in Secret `cluster-apps-vars-terraform-secret`
  path: ${CLUSTER_PATH}/flux/cluster-apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  timeout: 10m
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-apps-vars-terraform-secret
      - kind: Secret
        name: cluster-apps-secrets
      - kind: Secret
        name: cluster-apps-group-secrets
