# Kustomization for sources are needed, because they will be used as "dependency"
# for "applications"
# Sources must be installed "first"

apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: sources
  namespace: flux-system
spec:
  interval: 5m0s
  # Variables are taken from `flux-system/gotk-sync.yaml` stored in ConfigMap `cluster-apps-vars-terraform`
  path: ${CLUSTER_PATH}/flux/sources
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 2m0s
  wait: true
