apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: metrics-server
spec:
  chart:
    spec:
      chart: metrics-server
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system
      version: 3.10.0
  interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: metrics-server-group-helmrelease-values
      optional: true
    - kind: ConfigMap
      name: metrics-server-cluster-helmrelease-values
      optional: true
