apiVersion: v1
kind: Secret
metadata:
  name: pgpassfile
  namespace: pgadmin4
type: Opaque
stringData:
  # https://www.postgresql.org/docs/9.4/libpq-pgpass.html
  pgpassfile: |
    cnpg-db01-rw.cnpg-db01.svc.cluster.local:5432:postgres:${CNPG_DB01_SUPERUSER_USERNAME}:${CNPG_DB01_SUPERUSER_PASSWORD}
