apiVersion: v1
kind: Secret
metadata:
    name: cluster-apps-secrets
    namespace: flux-system
type: Opaque
data:
    USER_NAME: ENC[AES256_GCM,data:tEdbzzTGjCY=,iv:EyOIAq/3DPvLiwGkCl+QgUAJJokFbJY1cIUM6FHQVJk=,tag:uXdufSdBQLDvyqB5uAE9Sg==,type:str]
    PASSWORD: ENC[AES256_GCM,data:ucmwBSctC6s9LnWdhAuivA==,iv:58O8QV2Cr2SGl2XU3fV3LwDLyTCYjTISEUkEEulmzBg=,tag:jhHH0pWM6/q+EAlJtU7/CQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-central-1:729560437327:alias/sops
          created_at: "2022-06-17T18:33:24Z"
          enc: AQICAHi6LQQvIhnSAvomoXCu+jcBZlWiugdvqoPaQnWm1x1PbwEhTqsFEQT0jvPZy38hzgTIAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMgElGoHUf1Ua7SXNMAgEQgDulYh8EmRG1iRwuyVieUkc6cQHw0aum45JjXO7Vi4IsDksojSSVJs8AbQqnviuoP7hCgshVbcFHHhJA6Q==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-07T06:22:49Z"
    mac: ENC[AES256_GCM,data:2MrO5R2sftjGvSCjeRdsPup/LyEmxDoKuT4Q4Qxxojwg5btU7JPyGzbHPmS9yEguYzkUByz1IwNBx+MRXS+68R3xM14yGNI6O8HbZArKB78dg0y0duJbAfQ5EuBwxlFw0qOd0RxYlIvO2nzIQry15DJZVQ90rxEWK8O9OvHMSOk=,iv:BXHTFtgClST7EEWQ7LKwcUcV2wHcl4I964y0dkcVScM=,tag:AsxD0S0RscCFta87lgqxdQ==,type:str]
    pgp:
        - created_at: "2022-07-07T06:22:49Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFOA4duewNlKmHnEAf9EnHgboWtazl/TFR2FHWt0X0Cm5XcR6yA0hRoaa5UWZpf
            zeh+kx6Y0ugAhSOiyl5c82RUimeBjedUynXMoizt/bVqGRP9q3AScJQjwgCvhtmw
            l0AKoQynP7qY3apil2nAD0ESziMJILICLhd3S98L7FjB4disdsDI90N4FWtx6WB1
            6Xy5a9/lzPQN6LVo1x4YsAo0NQtI6CaauXgv3VqDQHvjg9bwP8Ar0xnrM1klzkLZ
            Re4Mle/Lr37AQqqVb5edej0zxGHBkZEPBrV1qNwRMUYwGS4UPYitwb+psuCMriWE
            YoF/2b0QbHS8s2DH+x7Y0yih0DgD6g/EuXhGbdSkDgf/WwYi9ZKTij+ZUveT9+sh
            vbeewmgjdebFlM1hRXQ9fvUeuSyjQM2eSWgaxjakV/e+uEbYWnWUmfSC72PoaJfg
            SneCIxk/cMGp11SHG0vYIUhQHd4hQ0fcVLYZiRdFS1/6hLj50kyfK8+LUdC+6pRd
            YCFG82NS0YeV7kz02VbqdWL1MZoBlpRF4hrtCNVTgFl0r09Lc0lTihSzYS7PNTx2
            nAOXjzIrjAreR0HQaGtTAZCDETcy2MZIcXdtfhs1gP0YIIKNGGlDBj700MAFmzrl
            QvvWj/ZXPPOUkV9CLcH/n8YBwz15o4nWaasMMFf0GQWnML8InCvv3ZE62EJjcKNv
            vtJRAZyE3GIAge2h64AgwQqUGuU7akbGfvW3F5QS+Z+KMYMM1Z6C/N8qPJMN3eaf
            RIC6lvTQfB3Uivpx9Y51dZfr/UAH+/0A7N6Ge2VIr5bGf+iQ
            =/dKp
            -----END PGP MESSAGE-----
          fp: 431A7F3379B5B00519077B732BD87EC4BA898363
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
