apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crossplane-provider
  namespace: flux-system
spec:
  dependsOn:
    - name: crossplane
  interval: 5m
  path: ${CLUSTER_PATH}/flux/cluster-apps/crossplane-aws-provider/crossplane-kustomization-provider/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-apps-vars-terraform-secret
