server:
  additionalApplications:
  - name: app-of-apps-initial-argocd
    namespace: argocd
    project: app-of-apps-initial-argocd
    source:
      repoURL: https://github.com/argoproj/argocd-example-apps.git
      targetRevision: HEAD
      path: apps
    destination:
      server: https://kubernetes.default.svc
      namespace: argocd
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
  additionalProjects:
  - name: app-of-apps-initial-argocd
    namespace: argocd
    sourceRepos:
    - '*'
    destinations:
    - namespace: '*'
      server: '*'
    clusterResourceWhitelist:
    - group: '*'
      kind: '*'
