apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  interval: 5m
  path: flux/cluster-apps/kube-prometheus-stack/kube-prometheus-stack-helmrelease-kustomization
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
