apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: 6.13.3
  interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: external-dns-group-helmrelease-values
      optional: true
    - kind: ConfigMap
      name: external-dns-cluster-helmrelease-values
      optional: true
