# https://github.com/rancher/rancher/blob/release/v2.7/chart/values.yaml
hostname: rancher.${CLUSTER_FQDN}
ingress:
  ingressClassName: nginx
  extraAnnotations:
    forecastle.stakater.com/expose: "true"
    forecastle.stakater.com/icon: "https://rancher.com/assets/img/logos/rancher-logo-horiz-color.svg"
    forecastle.stakater.com/appName: Rancher
  tls:
    source: letsEncrypt
letsEncrypt:
  email: ${EMAIL}
  environment: ${LETSENCRYPT_ENVIRONMENT}
  ingress:
    class: nginx
replicas: 1
bootstrapPassword: ${RANCHER_BOOTSTRAP_PASSWORD}
global:
  cattle:
    psp:
      enabled: false
