apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cnpg-db01
  namespace: flux-system
spec:
  dependsOn:
    - name: cnpg
    - name: kube-prometheus-stack
  interval: 5m
  path: ${CLUSTER_PATH}/../flux/cluster-apps/cnpg-db01/cnpg-db01-kustomization
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  timeout: 10m
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-apps-vars-terraform-secret
      - kind: Secret
        name: cluster-apps-group-secrets
      - kind: Secret
        name: cluster-apps-secrets
