apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager-crds
    - name: kube-prometheus-stack
  interval: 5m
  path: flux/cluster-apps/cert-manager/cert-manager-helmrelease-kustomization
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
