apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-crds
  namespace: flux-system
spec:
  interval: 5m
  path: flux/cluster-apps/cert-manager/cert-manager-crds-kustomization
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
