apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../flux/sources/autoscaler
  - ../../../../flux/sources/codecentric
  - ../../../../flux/sources/dex
  - ../../../../flux/sources/bitnami
  - ../../../../flux/sources/ingress-nginx
  - ../../../../flux/sources/jetstack
  - ../../../../flux/sources/kyverno
  - ../../../../flux/sources/metrics-server
  - ../../../../flux/sources/oauth2-proxy
  - ../../../../flux/sources/prometheus-community
  - ../../../../flux/sources/policy-reporter
  - ../../../../flux/sources/secrets-store-csi-driver
  - ../../../../flux/sources/vmware-tanzu
