apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: policy-reporter
  namespace: policy-reporter
spec:
  chart:
    spec:
      chart: policy-reporter
      sourceRef:
        kind: HelmRepository
        name: policy-reporter
        namespace: flux-system
      version: 2.19.4
  interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: policy-reporter-group-helmrelease-values
      optional: true
    - kind: ConfigMap
      name: policy-reporter-cluster-helmrelease-values
      optional: true
