# yamllint disable
# https://github.com/argoproj/argo-helm/blob/0453552b320712d20be65d9ba3f56644842dd84c/charts/argocd-apps/templates/applications.yaml
{{- range .Values.applications }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  {{- with .additionalAnnotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  {{- with .additionalLabels }}
  labels:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  name: {{ .name }}
  {{- with .namespace }}
  namespace: {{ . }}
  {{- end }}
  {{- with .finalizers }}
  finalizers:
    {{- toYaml . | nindent 8 }}
  {{- end }}
spec:
  project: {{ tpl .project $ }}
  source:
    {{- toYaml .source | nindent 8 }}
  destination:
    {{- toYaml .destination | nindent 8 }}
  {{- with .syncPolicy }}
  syncPolicy:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- with .ignoreDifferences }}
  ignoreDifferences:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- with .info }}
  info:
    {{- toYaml . | nindent 8 }}
  {{- end }}
{{- end }}
