apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true
  labels:
    type: group-helmrelease-values

configMapGenerator:
  - name: oauth2-proxy-group-helmrelease-values
    namespace: oauth2-proxy
    files:
      - values.yaml=oauth2-proxy-group-helmrelease-values.yaml

configurations:
  - kustomizeconfig.yaml
