apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dex
  namespace: dex
spec:
  chart:
    spec:
      chart: dex
      sourceRef:
        kind: HelmRepository
        name: dex
        namespace: flux-system
      version: 0.14.3
  interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: dex-group-helmrelease-values
      optional: true
    - kind: ConfigMap
      name: dex-cluster-helmrelease-values
      optional: true
