apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pgadmin4
  namespace: pgadmin4
spec:
  chart:
    spec:
      chart: pgadmin4
      sourceRef:
        kind: HelmRepository
        name: runix
        namespace: flux-system
      version: 1.15.4
  interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: pgadmin4-group-helmrelease-values
      optional: true
    - kind: ConfigMap
      name: pgadmin4-cluster-helmrelease-values
      optional: true
