apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: pgadmin4
  namespace: flux-system
spec:
  interval: 5m
  path: flux/cluster-apps/pgadmin4/pgadmin4-helmrelease-kustomization
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
