apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: aws-ebs-csi-driver
  namespace: flux-system
spec:
  dependsOn:
    - name: external-snapshotter
  interval: 5m
  path: flux/cluster-apps/aws-ebs-csi-driver/aws-ebs-csi-driver-helmrelease-kustomization
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
