apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: pkg-aws-provider
  namespace: crossplane-system
spec:
  # renovate: datasource=github-tags depName=crossplane-contrib/provider-aws extractVersion=^(?<version>.*)$
  package: crossplanecontrib/provider-aws:v0.33.0
  controllerConfigRef:
    name: pkg-aws-controllerconfig
