apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aws-kuard-secretproviderclass
  namespace: kuard
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: secretsmanager-kuard-secret
        objectType: secretsmanager
        jmesPath:
          - path: USERNAME
            objectAlias: USERNAME
          - path: PASSWORD
            objectAlias: PASSWORD
          - path: USERNAME_2
            objectAlias: USERNAME_2
          - path: PASSWORD_2
            objectAlias: PASSWORD_2
  secretObjects:
    # checkov:skip=CKV_SECRET_6 "Base64 High Entropy String"
    - secretName: secretsmanager-kuard-secret
      type: Opaque
      labels:
        app: kuard
      data:
        - objectName: USERNAME
          key: USERNAME
        - objectName: PASSWORD
          key: PASSWORD
        - objectName: USERNAME_2
          key: USERNAME_2
        - objectName: PASSWORD_2
          key: PASSWORD_2
