apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: forecastle
  namespace: flux-system
spec:
  interval: 5m
  path: flux/cluster-apps/forecastle/forecastle-helmrelease-kustomization
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
