apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../flux/cluster-apps/podinfo

configMapGenerator:
  - name: podinfo-group-helmrelease-values
    namespace: podinfo
    files:
      - values.yaml=podinfo-group-helmrelease-values.yaml

configurations:
  - kustomizeconfig.yaml
