ui:
  color: "#34577c"
  message: "group-helmrelease-values"
ingress:
  enabled: true
  className: nginx
  hosts:
    - host: ${CLUSTER_FQDN}
      paths:
        - path: /
          pathType: ImplementationSpecific
