apiVersion: v1
kind: Secret
metadata:
  name: kuard-secret
  namespace: crossplane-system
type: Opaque
data:
  USERNAME: ${CROSSPLANE_AWS_KUARD_SECRET_USERNAME}
  PASSWORD: ${CROSSPLANE_AWS_KUARD_SECRET_PASSWORD}
  USERNAME_2: ${CROSSPLANE_AWS_KUARD_SECRET_USERNAME}
  PASSWORD_2: ${CROSSPLANE_AWS_KUARD_SECRET_PASSWORD}
