apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: forecastle
  namespace: flux-system
spec:
  interval: 1h
  url: https://github.com/stakater/Forecastle.git
  ref:
    branch: master
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/deployments/kubernetes/chart/
