name: checkov

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
    paths:
      - cloudformation/**
      - terraform/**

jobs:
  checkov:
    name: Run checkov sarif report
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Run checkov
        uses: bridgecrewio/checkov-action@master
        with:
          # Skip ArgoCD checks
          skip_check: CKV_ARGO_1,CKV_ARGO_2
          output_format: sarif
          quiet: true

      - name: Upload SARIF file
        if: ${{ github.actor!= 'dependabot[bot]' }}
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
