name: clusters-aws-schedule

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

env:
  SCHEDULED_CLUSTERS: ".*(/mgmt02.k8s.use1.dev.proj.aws.mylabs.dev$).*"
  # https://github.com/kubernetes/kubectl/releases
  KUBECTL_VERSION: "v1.22.8"

jobs:
  scheduled-run-time-check:
    name: "Scheduled run time check"
    runs-on: ubuntu-latest
    outputs:
      scheduled_run: ${{ steps.scheduled_run.outputs.scheduled_run }}
      scheduled_clusters: ${{ steps.scheduled_run.outputs.scheduled_clusters }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: 💡 Scheduled run time check
        id: scheduled_run
        run: |
          set -euxo pipefail

          # Check if there was a change in git repo in passed 24 hours
          # https://github.community/t/trigger-action-on-schedule-only-if-there-are-changes-to-the-branch/17887/4
          if [[ -z "$(git rev-list --after='24 hours' ${{ github.sha }})" ]]; then
            echo "*** Git repository hasn't been changed in passed 24 hours - skipping next tasks..."
            echo "::set-output name=scheduled_run::false"
          fi
          # This is workaround for: https://github.community/t/reusable-workflow-env-context-not-available-in-jobs-job-id-with/206111/3
          echo "::set-output name=scheduled_clusters::${SCHEDULED_CLUSTERS}"

  scheduled-create:
    name: "sched"
    needs: scheduled-run-time-check
    if: ${{ needs.scheduled-run-time-check.outputs.scheduled_run != 'false' }}
    uses: ./.github/workflows/clusters-aws-reusable-workflow.yml
    with:
      clusters: ${{ needs.scheduled-run-time-check.outputs.scheduled_clusters }}
      terraform_action: apply
      env-variables: "'TF_LOG=ERROR' 'TF_DATA_DIR=.terraform'"
    secrets:
      CREATE_FLUX_DEPLOY_KEY_GITHUB_TOKEN: ${{ secrets.CREATE_FLUX_DEPLOY_KEY_GITHUB_TOKEN }}

  scheduled-check:
    name: "Test cluster access"
    needs: [scheduled-run-time-check, scheduled-create]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: 💡🔪 Check out repository code
        uses: actions/checkout@v3

      - name: 💡🔪 Install necessary tools/packages
        run: |
          set -euxo pipefail
          sudo apt update -qq
          sudo apt-get install -y -qq curl gettext-base git jq unzip > /dev/null

          if ! command -v aws &> /dev/null; then
            curl -sL "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"
            unzip -q -o /tmp/awscliv2.zip -d /tmp/
            sudo /tmp/aws/install
          fi

      - name: Setup kubectl
        uses: azure/setup-kubectl@v2.1
        with:
          version: ${{ env.KUBECTL_VERSION }}

      - name: Setup Flux
        uses: fluxcd/flux2/action@main

      - name: 💡🔪 Get and display environment variables
        run: |
          set -euxo pipefail

          get_variable_from_group_cluster_tfvars () {
            local CLUSTER_PATH="$1" TF_CODE_VARIABLE="$2" VARIABLE_HELPER
            if grep -q "${TF_CODE_VARIABLE}" "${CLUSTER_PATH}/cluster-variables.tfvars" ; then
              VARIABLE_HELPER=$(awk -F \" "/^${TF_CODE_VARIABLE}/ { print \$2 }" "${CLUSTER_PATH}/cluster-variables.tfvars")
            else
              VARIABLE_HELPER=$(awk -F \" "/^${TF_CODE_VARIABLE}/ { print \$2 }" "${CLUSTER_PATH}/../group-variables.tfvars")
            fi
            echo -e "\n💡 Variable: \"${TF_CODE_VARIABLE^^}\" = \"${VARIABLE_HELPER}\""
            echo "${TF_CODE_VARIABLE^^}=${VARIABLE_HELPER}" >> "${GITHUB_ENV}"
            export "${TF_CODE_VARIABLE^^}=${VARIABLE_HELPER}"
            echo "::set-output name=${TF_CODE_VARIABLE^^}::${VARIABLE_HELPER}"
          }

          CLUSTER_PATH=$(find clusters -maxdepth 2 -mindepth 2 -type d -regextype "posix-extended" ! -regex '.*/(argocd|flux)' -regex '.*${{ env.SCHEDULED_CLUSTERS }}.*')

          get_variable_from_group_cluster_tfvars "${CLUSTER_PATH}" "aws_default_region"
          get_variable_from_group_cluster_tfvars "${CLUSTER_PATH}" "aws_assume_role"
          get_variable_from_group_cluster_tfvars "${CLUSTER_PATH}" "cluster_fqdn"
          echo "CLUSTER_NAME=${CLUSTER_FQDN%%.*}" | tee -a "${GITHUB_ENV}"

      - name: 💡🔪 Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.AWS_ASSUME_ROLE }}
          role-session-name: GitHubOidcFederatedRole
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: 💡 Access Amazon EKS cluster and list nodes, Flux and ArgoCD details
        run: |
          set -euxo pipefail
          sleep 100
          export KUBECONFIG="/tmp/kubeconfig-${CLUSTER_NAME}.conf"
          aws eks update-kubeconfig --region "${AWS_DEFAULT_REGION}" --name "${CLUSTER_NAME}" --kubeconfig "${KUBECONFIG}"
          kubectl get nodes -o wide --show-labels
          kubectl get namespaces
          flux get all --all-namespaces
          kubectl get applications,applicationsets -A

  scheduled-delete:
    name: "sched"
    needs: [scheduled-run-time-check, scheduled-create, scheduled-check]
    if: ${{ needs.scheduled-run-time-check.outputs.scheduled_run != 'false' }}
    uses: ./.github/workflows/clusters-aws-reusable-workflow.yml
    with:
      # https://github.community/t/reusable-workflow-env-context-not-available-in-jobs-job-id-with/206111
      clusters: ${{ needs.scheduled-run-time-check.outputs.scheduled_clusters }}
      terraform_action: destroy
      env-variables: "'TF_LOG=ERROR' 'TF_DATA_DIR=.terraform'"
    secrets:
      CREATE_FLUX_DEPLOY_KEY_GITHUB_TOKEN: ${{ secrets.CREATE_FLUX_DEPLOY_KEY_GITHUB_TOKEN }}
