name: clusters-aws

on:
  workflow_dispatch:
    inputs:
      clusters:
        description: Cluster list
        # See details in `find` manual and look for `-regextype "posix-extended"` and `-regex`
        default: .*(/ruzickap01.k8s.use1.dev.proj.aws.mylabs.dev$|/aws-dev-sandbox/).*
        required: true
      action:
        type: choice
        description: Cluster Terraform action
        default: plan
        required: true
        options:
          - plan
          - apply
          - plan -destroy
          - destroy
          - destroy -lock=false
      env-variables:
        description: Environment variable(s)
        # 'TF_CLI_ARGS_destroy=-auto-approve -lock=false'
        default: "'TF_LOG=ERROR' 'TF_DATA_DIR=.terraform'"
        required: false
  # push:
  #   # Run pipeline in case there are any changes in these directories in `main` branch
  #   paths:
  #     # If you change this path change it also in the rest of the pipeline (variable can not be used)
  #     - 'clusters/dev-sandbox/**'
  #     - 'terraform/dev/**'
  #   branches:
  #     - main

jobs:
  cluster-aws-pipeline:
    name: "aws"
    uses: ./.github/workflows/clusters-aws-reusable-workflow.yml
    with:
      clusters: ${{ github.event.inputs.clusters }}
      terraform_action: ${{ github.event.inputs.action }}
      env-variables: ${{ github.event.inputs.env-variables }}
    secrets:
      CREATE_FLUX_DEPLOY_KEY_GITHUB_TOKEN: ${{ secrets.CREATE_FLUX_DEPLOY_KEY_GITHUB_TOKEN }}
