name: clusters-aws

on:
  workflow_dispatch:
    inputs:
      clusters:
        type: choice
        description: Cluster list
        # See details in `find` manual and look for `-regextype "posix-extended"` and `-regex`
        default: .*/mgmt01.k8s.use1.dev.proj.aws.mylabs.dev
        required: true
        options:
          - .*/aws-dev-mgmt/.*
          - .*/mgmt01.k8s.use1.dev.proj.aws.mylabs.dev
          - .*/mgmt02.k8s.use1.dev.proj.aws.mylabs.dev
      # clusters:
      #   description: Cluster list
      #   default: .*(/aws-dev-mgmt/|/mgmt01.k8s.use1.dev.proj.aws.mylabs.dev$).*
      #   required: true
      action:
        type: choice
        description: Cluster Terraform action
        default: plan
        required: true
        options:
          - plan
          - apply
          - plan -destroy
          - destroy
          - destroy -lock=false
      env-variables:
        description: Environment variable(s)
        # 'TF_CLI_ARGS_destroy=-auto-approve -lock=false'
        default: "'TF_LOG=ERROR' 'TF_DATA_DIR=.terraform'"
        required: false
  push:
    paths:
      - 'clusters/dev-sandbox/**'
      - 'terraform/dev/**'

permissions: read-all

jobs:
  cluster-aws-pipeline:
    name: "aws"
    uses: ./.github/workflows/clusters-aws-reusable-workflow.yml
    permissions:
      contents: read
      id-token: write
    with:
      clusters: ${{ github.event.inputs.clusters || '.*/mgmt01.k8s.use1.dev.proj.aws.mylabs.dev' }}
      terraform_action: ${{ github.event.inputs.action || 'plan' }}
      env-variables: ${{ github.event.inputs.env-variables }}
    secrets:
      CREATE_FLUX_DEPLOY_KEY_GITHUB_TOKEN: ${{ secrets.CREATE_FLUX_DEPLOY_KEY_GITHUB_TOKEN }}
