name: clusters-aws-schedule

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

env:
  SCHEDULED_CLUSTERS: ".*(/ruzickap01.k8s.use1.dev.proj.aws.mylabs.dev$).*"

jobs:
  scheduled-run-time-check:
    name: "Scheduled run time check"
    runs-on: ubuntu-latest
    outputs:
      scheduled_run: ${{ steps.scheduled_run.outputs.scheduled_run }}
      scheduled_clusters: ${{ steps.scheduled_run.outputs.scheduled_clusters }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 💡 Scheduled run time check
        id: scheduled_run
        run: |
          set -euxo pipefail

          # Check if there was a change in git repo in passed 24 hours
          # https://github.community/t/trigger-action-on-schedule-only-if-there-are-changes-to-the-branch/17887/4
          if [[ -z "$(git rev-list --after='24 hours' ${{ github.sha }})" ]]; then
            echo "*** Git repository hasn't been changed in passed 24 hours - skipping next tasks..."
            echo "::set-output name=scheduled_run::false"
          fi
          # This is workaround for: https://github.community/t/reusable-workflow-env-context-not-available-in-jobs-job-id-with/206111/3
          echo "::set-output name=scheduled_clusters::${SCHEDULED_CLUSTERS}"

  scheduled-create:
    name: "sched"
    needs: scheduled-run-time-check
    if: ${{ needs.scheduled-run-time-check.outputs.scheduled_run != 'false' }}
    uses: ./.github/workflows/clusters-aws-reusable-workflow.yml
    with:
      clusters: ${{ needs.scheduled-run-time-check.outputs.scheduled_clusters }}
      terraform_action: apply
      env-variables: "'TF_LOG=ERROR' 'TF_DATA_DIR=.terraform'"

  scheduled-delete:
    name: "sched"
    needs: [ scheduled-run-time-check, scheduled-create ]
    if: ${{ needs.scheduled-run-time-check.outputs.scheduled_run != 'false' }}
    uses: ./.github/workflows/clusters-aws-reusable-workflow.yml
    with:
      # https://github.community/t/reusable-workflow-env-context-not-available-in-jobs-job-id-with/206111
      clusters: ${{ needs.scheduled-run-time-check.outputs.scheduled_clusters }}
      terraform_action: destroy
      env-variables: "'TF_LOG=ERROR' 'TF_DATA_DIR=.terraform'"
