name: Update Flux

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-flux:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@main

      - name: Check for updates
        id: update
        run: |
          find clusters -name "gotk-components.yaml" -exec bash -c 'FILE="$1"; flux install --export > ${FILE}' shell {} \;
          echo "::set-output name=flux_version::$(flux -v)"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: update-flux
          commit-message: Update Flux to ${{ steps.update.outputs.flux_version }}
          title: Update Flux to ${{ steps.update.outputs.flux_version }}
          body: |
            ${{ steps.update.outputs.flux_version }}
