---
name: flux-validate

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
    paths:
      - .github/workflows/flux-validate.yaml
      - clusters/**.yml
      - flux/**.yaml
      - kustomization.yaml

env:
  # renovate: datasource=github-tags depName=yannh/kubeconform
  KUBECONFORM_VERSION: 0.6.6

permissions: read-all

jobs:
  flux-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - name: Intall kubeconform
        run: |
          curl -s -L "https://github.com/yannh/kubeconform/releases/download/v${{ env.KUBECONFORM_VERSION }}/kubeconform-$(uname | sed "s/./\L&/g")-amd64.tar.gz" -o - | tar xzf - -C /usr/local/bin/ kubeconform

      - name: Validate manifests
        run: ./scripts/flux-validate.sh
