name: main-eks

on:
  workflow_dispatch:
    inputs:
      action:
        type: choice
        description: Action
        default: create + delete
        options:
          - create
          - delete
          - create + delete
        required: true

env:
  MY_PASSWORD: ${{ secrets.MY_PASSWORD }}
  AWS_DEFAULT_REGION: eu-central-1
  AWS_GITHUB_OIDC_FEDERATED_ROLE_TO_ASSUME: ${{ secrets.AWS_GITHUB_OIDC_FEDERATED_ROLE_MAIN_EKS }}

concurrency: main-eks

jobs:
  create-main-eks:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2

      - name: 💡🔪 Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.AWS_GITHUB_OIDC_FEDERATED_ROLE_MAIN-EKS }}
          role-session-name: GitHubOidcFederatedRole
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: 💡 Create EKS cluster + environment
        if: ${{ contains(github.event.inputs.action, 'create') }}
        run: |
          ./create-k8s-eks-flux.sh
          kubectl get pods -A
          helm ls -A

      - name: 🔪 Delete EKS cluster + environment
        if: ${{ contains(github.event.inputs.action, 'delete') }}
        run: |
          ./delete-k8s-eks-flux.sh
