name: MegaLinter

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main

permissions: read-all

jobs:
  build:
    name: MegaLinter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Extract commands from markdown files
        run: |
          set -euxo pipefail
          echo '#!/usr/bin/env bash' > README.sh
          find . -name '*.md' -print0 | while IFS= read -r -d '' FILE ; do
            sed -n "/^\`\`\`\(bash\|shell\).*/,/^\`\`\`$/p" "${FILE}" \
            | \
            sed \
              -e 's/^```\(bash\|shell\).*//' \
              -e '/^```$/d' \
            >> README.sh
          done
          chmod a+x README.sh

      - name: MegaLinter
        uses: megalinter/megalinter@v6.22.0
        env:
          BASH_SHFMT_ARGUMENTS: --indent 2 --space-redirects
          BASH_SHFMT_FILTER_REGEX_EXCLUDE: scripts/flux-validate.sh
          DISABLE_LINTERS: COPYPASTE_JSCPD,CSS_STYLELINT,REPOSITORY_DEVSKIM,REPOSITORY_SEMGREP,REPOSITORY_TRIVY,SPELL_CSPELL,TERRAFORM_KICS,TERRAFORM_TERRASCAN,YAML_PRETTIER
          ENV_DOTENV_LINTER_FILTER_REGEX_EXCLUDE: cluster-apps.*\.env
          FORMATTERS_DISABLE_ERRORS: false
          GITHUB_COMMENT_REPORTER: false
          GITHUB_STATUS_REPORTER: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRINT_ALPACA: false
          SARIF_REPORTER: true
          # Skip "existant" in docs/theme/css/chrome.css
          SPELL_MISSPELL_ARGUMENTS: -i existant
          # Needed for scanning generated README.sh file
          VALIDATE_ALL_CODEBASE: true
          YAML_PRETTIER_FILTER_REGEX_EXCLUDE: argocd/cluster-addons/templates/.*
          YAML_YAMLLINT_FILTER_REGEX_EXCLUDE: '(argocd/cluster-addons/templates/|/flux-system/gotk-components\.yaml)'
