name: 'Close stale issues and PRs'

on:
  schedule:
    - cron: '30 1 * * *'

permissions:
  issues: write
  pull-requests: write

jobs:
  mark-stale-issues-and-prs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v7
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue appears to be stale because it has been open 30 days with no activity. This issue will be closed in 7 days unless `Stale` label is removed, a new comment is made, or `not-Stale` label is added.'
          exempt-issue-labels: 'not-Stale'
          stale-pr-message: 'This PR appears to be stale because it has been open 30 days with no activity. This PR will be closed in 7 days unless `Stale` label is removed, a new comment is made, or `not-Stale` label is added.'
          exempt-pr-labels: 'not-Stale'
          labels-to-remove-when-unstale: 'Stale'
          days-before-stale: 30
          days-before-close: 7
