name: tfsec

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
    paths:
      - cloudformation/**
      - terraform/**

jobs:
  tfsec:
    name: Run tfsec sarif report
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v1.3.1
        with:
          tfsec_args: --exclude-downloaded-modules
          github_token: ${{ github.token }}

      - name: Run tfsec
        uses: aquasecurity/tfsec-sarif-action@master
        with:
          tfsec_args: --exclude-downloaded-modules
          sarif_file: tfsec.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: tfsec.sarif
