name: tfsec

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
    paths:
      - cloudformation/**
      - terraform/**

jobs:
  tfsec:
    name: Run tfsec sarif report
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v1.1.0
        with:
          github_token: ${{ github.token }}

      - name: Run tfsec
        uses: tfsec/tfsec-sarif-action@v0.1.0
        with:
          sarif_file: tfsec.sarif

      - name: Upload SARIF file
        if: ${{ github.actor!= 'dependabot[bot]' }}
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: tfsec.sarif
